### ISSUE TITLE
build error using example code

### ISSUE THREAD

**Issue by thosmos** [MiroslavPetrik/form-atoms-field#27]
**Describe the bug**
I installed all of the dependencies and then added a new page in my NextJS project and pasted the sample code from this repo's readme file and got the following error: 

```
error - /Users/thomas/src/remvi/remvi-supabase/node_modules/.pnpm/@form-atoms+field@2.5.5_gq3kuvvvnmquvd2l24akkqjwwy/node_modules/@form-atoms/field/dist/index.js:1
export * from "./components";
^^^^^^

SyntaxError: Unexpected token 'export'
    at compileFunction (<anonymous>)
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1084:15)
    at Module._compile (node:internal/modules/cjs/loader:1119:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.@form-atoms/field (/Users/thomas/src/remvi/remvi-supabase/.next/server/pages/flowbite.js:32:18)
    at __webpack_require__ (/Users/thomas/src/remvi/remvi-supabase/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/flowbite.tsx:6:75)
    at Function.__webpack_require__.a (/Users/thomas/src/remvi/remvi-supabase/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/flowbite.tsx:1:21)
    at Object../pages/flowbite.tsx (/Users/thomas/src/remvi/remvi-supabase/.next/server/pages/flowbite.js:22:1)
    at __webpack_require__ (/Users/thomas/src/remvi/remvi-supabase/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/thomas/src/remvi/remvi-supabase/.next/server/pages/flowbite.js:72:39)
    at /Users/thomas/src/remvi/remvi-supabase/.next/server/pages/flowbite.js:73:28
    at Object.<anonymous> (/Users/thomas/src/remvi/remvi-supabase/.next/server/pages/flowbite.js:76:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/Users/thomas/src/remvi/remvi-supabase/node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/require.js:88:12)
    at /Users/thomas/src/remvi/remvi-supabase/node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/load-components.js:49:73
    at async Object.loadComponentsImpl [as loadComponents] (/Users/thomas/src/remvi/remvi-supabase/node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/load-components.js:49:26)
    at async DevServer.findPageComponentsImpl (/Users/thomas/src/remvi/remvi-supabase/node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:599:36) {
  page: '/flowbite'
}
```

**To Reproduce**
1. Copy code into new page at /pages/flowbite.tsx
2. pnpm install jotai form-atoms @form-atoms/field @testing-library/dom  zod@^3 @form-atoms/flowbite
3. pnpm run dev
4. navigate to /flowbite

**Expected behavior**
The example code should "just work"

**Comment by MiroslavPetrik** [comment]
@thosmos closing this as it works with the latest version. Happily using with next.js
